# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Workflow Self-Test (Rockcraft Cache)

on:
  pull_request:
  
jobs:
  save-cache:
    uses: ./.github/workflows/build_rocks.yaml
    secrets: inherit
    with:
      working-directory: "tests/workflows/rock/"
      cache-action: save

  restore-cache:
    needs: [ save-cache ]
    uses: ./.github/workflows/build_rocks.yaml
    secrets: inherit
    with:
      working-directory: "tests/workflows/rock/"
      cache-action: restore

  scan-images:
    needs: restore-cache
    uses: ./.github/workflows/scan_images.yaml
    secrets: inherit
    with:
      images: ${{ needs.restore-cache.outputs.images }}
      trivy-image-config: ./trivy.yaml
      upload-result: true
